name = "babaquinha"
main = "worker.js"
compatibility_date = "2024-12-15"

# Workers configuration
workers_dev = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "babaquinha"
database_id = "8f58c2f3-1862-4228-a60e-d558ae854227"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
[observability.traces]
enabled = true

[env.production]
name = "babaquinha-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "babaquinha"
database_id = "8f58c2f3-1862-4228-a60e-d558ae854227"
